## Build the Docker image
## Push the Docker image to docker hub
## SSH into our VM and start the new image 

name: Deploy frontend
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.frontend
          build-args: 
              DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: rohinigarg/todo-app-frontend:${{ github.sha }}